#!/bin/sh -e

export PACKAGE=mkdocs2
export PYTHONPATH=.:${PYTHONPATH}
export PYTHONVERSION=`python -c 'import sys; print("%d.%d" % sys.version_info[:2])'`
export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

${PREFIX}pytest --cov ${PACKAGE} --cov tests --cov-fail-under 100 ./tests/ --cov-report term-missing
${PREFIX}mypy --ignore-missing-imports --disallow-untyped-defs ${PACKAGE}
if [[ ${PYTHONVERSION} == "3.6" ]]; then
    ${PREFIX}black ${PACKAGE} tests --check
fi
